In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
df = pd.read_csv('bitcoin.csv')
df.head()

         Date  Open  High   Low  Close    Vol.
0  2013-01-01  13.5  13.6  13.2   13.3  28.41K
1  2013-01-02  13.3  13.4  13.2   13.3  17.97K
2  2013-01-03  13.3  13.5  13.3   13.4  18.03K
3  2013-01-04  13.4  13.5  13.3   13.5  29.64K
4  2013-01-05  13.5  13.6  13.3   13.4  21.33K

In [3]:
df.shape

(3793, 6)

               Open          High           Low         Close
count   3793.000000   3793.000000   3793.000000   3793.000000
mean   11233.252307  11529.297996  10904.581545  11240.315766
std    15421.568722  15827.119004  14960.319732  15422.533996
min       13.300000     13.400000     13.200000     13.300000
25%      450.300000    459.600000    441.900000    451.400000
50%     5208.300000   5322.900000   5033.700000   5209.100000
75%    14976.200000  15648.300000  13902.300000  15043.000000
max    67528.700000  68990.600000  66334.900000  67527.900000

In [ ]:
df.describe()